sudo: required
dist: trusty

language: ruby

env:
  - DB=postgres
  - DB=mysql

gemfile:
  - gemfiles/spree_3_1.gemfile
  - gemfiles/spree_3_2.gemfile
  - gemfiles/spree_3_3.gemfile
  - gemfiles/spree_3_4.gemfile
  - gemfiles/spree_master.gemfile

script:
  - bundle exec rake test_app
  - bundle exec rake spec

rvm:
  - 2.5.0
  - 2.4.3
  - 2.3.6
  - 2.2.9

before_install:
  - mysql -u root -e "GRANT ALL ON *.* TO 'travis'@'%';"
